In [19]:
import string
p = string.punctuation
d = string.digits
#print(p)
#print(d)
with open('Obamacare_Red_Consolidated.csv','r') as infile:
    content = infile.read()
    list1 = content.lower().splitlines()
#list1 = ['life is good##3 sh et','https:\\Hell a lot of problems ate','7537Https@ Trump is great ']
no_punctuation = []
no_digits = []
for i in list1:
    #print i
    table_p = string.maketrans(p, len(p) * " ")
    table_d = string.maketrans(d, len(d) * " ")
    #print table_p
    #print table_d
    no_punctuation.append(i.translate(table_p))
    #no_digits.append(str_without_punct.lower().translate(table_d))
    #print no_punctuation
    #print no_digits
    
print len(no_punctuation)

for i in no_punctuation:
    no_digits.append(i.lower().translate(table_d))
print len(no_digits)

1078
1078


In [20]:
#list2 = []
import nltk
stopwords = nltk.corpus.stopwords.words('english')
#print type(stopwords), len(stopwords), stopwords

lst2=['trump','donald','http','https','u','n','via' , 'btw' , 'hey', 'amp','say',
      'president','nhttps','russia','obama','would','like','one','new','news']
stopwords=stopwords+lst2
#print stopwords



list_of_str = []
for i in no_digits:
    str = []
    str = i.split()
    #print str
    list2 = []
    #list_without_stopwords2 = []
    for word in str:
        if word not in stopwords and len(word)>3:
            #list2 = []
            list2.append(word)
            
           
    str_without_punct = ' '.join(list2)
    #print str_without_punct
    list_of_str.append(str_without_punct)
print list_of_str[:11]

C:\Program Files\Anaconda2\lib\site-packages\ipykernel\__main__.py:21: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal


['\xef\xbb\xbfit critical acquiring government benefits modified adjusted gross income possible obamacare', 'beckydeplorable boom obamacare repeal gains momentum reps jump board pqnnayspjc', 'keithellison', 'sethdavishoops insurance affordable americans rich poor admf', 'guys suck worse uzzrk wjiq', 'washingtonpost exactly house voted pass obamacare replacement hqbrrrc', 'joyannreid keep estimates bill medicare payments states billion next', 'thehill obamacare repeal bill contains exemption members congress staffs zgkh', 'andrew davidfrum find conservative nevertrumper suicide watch demise obamacare', '', 'theghermguys gherm preexistingcondition donaldtrump trumpcare obamacare healthcare']


In [21]:
outfile = open('Final_corpus_for_topic_modelling_Obama_RedStates.txt', 'w')
for tweet in list_of_str:
    outfile.write(tweet)
    outfile.write('\n')
    
outfile.close()

In [22]:
import numpy as np  # a conventional alias
import glob
import os
import string
import nltk
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity
from scipy.cluster.hierarchy import ward, dendrogram
from sklearn.manifold import MDS
import matplotlib.pyplot as plt
import scipy.stats as stats

In [23]:
import string
corpus = []

with open('Final_corpus_for_topic_modelling_Obama_RedStates.txt','r') as infile:
    content = infile.read()
    corpus = content.lower().splitlines()
    infile.close()

In [24]:
for idx in range(len(corpus)-1, 1, -1):
    print
    #print names[idx]
    print corpus[idx][:100].replace('\n', ' ')


peterdaou trumprussia percolating chaffetz going oreilly gone flynn finished obamacare alive democra

wvjoe doomed republicans vowing never give killing people repealing obamacare politicususa

reprwilliams funny voters longer obamacare realize pxhsruzpe

opinion plan destroy obamacare even crueler ptgiinxw samswey nvey

repeal replace even repealed obamacare today policyholders still covered years message

republicans float obamacare replacement plan grpkfxv foxnews android

give obamacare repeal another shot next week eyob finance

adamsflafan white house plans obamacare showdown next week bavpezh politico

landangel gops obamacare repeal deal give states choicebut federal permission pffesnljqk

socialpowerone msnbc panel believe paul ryan wants repeal obamacare

obsoletedogma well take obamacare subsidies away poor people dont help repeal obamacare plan

noahcrothman republicans learned nothing obamacare repeal replace debacle great udrxe

brianbeutler cancer republicans think prem

In [25]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', min_df=2)
doc_term_matrix = vectorizer.fit_transform(corpus)
print doc_term_matrix.shape
vocab = vectorizer.get_feature_names() # list of unique vocab, we will use this later
print len(vocab), '# of unique words'
print vocab[-10:]
print vocab[:10]

(1078, 963)
963 # of unique words
[u'wouldnt', u'wvjoe', u'yeah', u'year', u'years', u'youtube', u'zaibatsunews', u'zero', u'zerohedge', u'zfmma']
[u'abbygoodnough', u'able', u'abominableca', u'acarepeal', u'accountable', u'acha', u'action', u'actually', u'adamsflafan', u'address']


In [26]:
from sklearn import decomposition

print 'num of documents, num of unique words'
print doc_term_matrix.shape

num_topics = 10

clf = decomposition.NMF(n_components=num_topics, random_state=1)
doctopic = clf.fit_transform(doc_term_matrix)
print num_topics, clf.reconstruction_err_

num of documents, num of unique words
(1078, 963)
10 29.8503907059


In [27]:
topic_words = []
num_top_words = 5

print vocab[100]

for topic in clf.components_:
    #print topic.shape, topic[:10]
    word_idx = np.argsort(topic)[::-1][:num_top_words]
    print word_idx
    for idx in word_idx:
        print vocab[idx],
    print
for topic in clf.components_:
    print topic.shape, topic[:5]
    word_idx = np.argsort(topic)[::-1][0:num_top_words] # get indexes with highest weights
    print 'top indexes', word_idx
    topic_words.append([vocab[i] for i in word_idx])
    print topic_words[-1]
    print

print '__lol__' * 10    
    
    
for t in range(len(topic_words)):
    print "Topic {}: {}".format(t, ' '.join(topic_words[t][:15]))

chronic
[686 555 692 842 788]
repeal obamacare replace thehill standwithhfc
[  2 431 460 620 555]
abominableca justrepeal letthemarketreplace poltoons obamacare
[103 115 125 163 555]
city collapse complete dailycaller obamacare
[345  80  27 521  19]
health care americans millions ahca
[590 763 501 230  26]
people sick mean emerging american
[622 876  42 704 575]
popular trumpcare backfires republican party
[555 694 346 876 602]
obamacare replacement healthcare trumpcare plan
[910 376 857 940 605]
vote house thursday white plans
[705 911 842 437 507]
republicans voted thehill killing meet
[357 116 822 105 419]
help college taneuk class jimmykimmel
(963L,) [ 0.01427908  0.          0.          0.          0.01100122]
top indexes [686 555 692 842 788]
[u'repeal', u'obamacare', u'replace', u'thehill', u'standwithhfc']

(963L,) [ 0.          0.          0.84967256  0.          0.        ]
top indexes [  2 431 460 620 555]
[u'abominableca', u'justrepeal', u'letthemarketreplace', u'poltoons',